"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChainData = void 0;
exports.ChainData = {
    1: {
        chainId: 1,
        chainIdHex: "0x1",
        name: "Ethereum Mainnet",
        currencyName: "Ether",
        currencySymbol: "ETH",
        blockExplorerUrl: "https://etherscan.io",
        rpcUrl: null,
    },
    5: {
        chainId: 5,
        chainIdHex: "0x5",
        name: "Goerli Testnet",
        currencyName: "Goerli Ether",
        currencySymbol: "GOE",
        blockExplorerUrl: "https://goerli.etherscan.io",
        rpcUrl: null,
    },
    42161: {
        chainId: 42161,
        chainIdHex: "0xa4b1",
        name: "Arbitrum One",
        currencyName: "Ether",
        currencySymbol: "ETH",
        blockExplorerUrl: "https://arbiscan.io",
        rpcUrl: null,
    },
    10: {
        chainId: 10,
        chainIdHex: "0xa",
        name: "Optimism",
        currencyName: "Ether",
        currencySymbol: "ETH",
        blockExplorerUrl: "https://optimistic.etherscan.io",
        rpcUrl: null,
    },
    137: {
        chainId: 137,
        chainIdHex: "0x89",
        name: "Polygon Mainnet",
        currencyName: "Matic",
        currencySymbol: "MATIC",
        blockExplorerUrl: "https://polygonscan.com",
        rpcUrl: null,
    },
    100: {
        chainId: 100,
        chainIdHex: "0x64",
        name: "xDai Chain",
        currencyName: "xDai",
        currencySymbol: "xDAI",
        blockExplorerUrl: "https://blockscout.com/poa/xdai",
        rpcUrl: null,
    },
    56: {
        chainId: 56,
        chainIdHex: "0x38",
        name: "Binance Smart Chain",
        currencyName: "Binance Coin",
        currencySymbol: "BNB",
        blockExplorerUrl: "https://bscscan.com",
        rpcUrl: null,
    },
    97: {
        chainId: 97,
        chainIdHex: "0x61",
        name: "Binance Smart Chain Testnet",
        currencyName: "Binance Coin",
        currencySymbol: "BNB",
        blockExplorerUrl: "https://testnet.bscscan.com",
        rpcUrl: null,
    },
    43114: {
        chainId: 43114,
        chainIdHex: "0xa86a",
        name: "Avalanche C-Chain",
        currencyName: "Avalanche",
        currencySymbol: "AVAX",
        blockExplorerUrl: "https://snowtrace.io/",
        rpcUrl: null,
    },
    43113: {
        chainId: 43113,
        chainIdHex: "0xa869",
        name: "Avalanche FUJI C-Chain",
        currencyName: "Avalanche",
        currencySymbol: "AVAX",
        blockExplorerUrl: "https://testnet.snowtrace.io/",
        rpcUrl: null,
    },
    250: {
        chainId: 250,
        chainIdHex: "0xfa",
        name: "Fantom Opera",
        currencyName: "Fantom",
        currencySymbol: "FTM",
        blockExplorerUrl: "https://ftmscan.com",
        rpcUrl: null,
    },
    4002: {
        chainId: 4002,
        chainIdHex: "0xfa2",
        name: "Fantom Testnet",
        currencyName: "Fantom",
        currencySymbol: "FTM",
        blockExplorerUrl: "https://testnet.ftmscan.com/",
        rpcUrl: null,
    },
};
